# Generated by Django 5.2.4 on 2025-07-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
    ]
