# Generated by Django 5.2.4 on 2025-07-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='loginid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
