# Generated by Django 5.2.4 on 2025-07-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_profile_image_alter_student_enroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll',
            field=models.CharField(max_length=20),
        ),
    ]
